services:
  notesapp:
    build:
      context: .
      dockerfile: NotesApp/Dockerfile
    ports:
      - "8080:80"
    networks:
      - appnetwork
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=NotesApp;User Id=sa;Password=HardPassword123;MultipleActiveResultSets=true;TrustServerCertificate=True 
  
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=HardPassword123
    ports:
      - "1433:1433"
    networks:
      - appnetwork

networks:
  appnetwork: